/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sapasemua.view;

import sapasemua.model.*;

/**
 *
 * @author juven
 */
public class QuizAlfabet extends javax.swing.JFrame {
    private Kuis kuis;

    /**
     * Creates new form QuizAlfabet
     */
    public QuizAlfabet(Kuis kuis) {
        initComponents();
        this.kuis = kuis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AnswerButtonGroup = new javax.swing.ButtonGroup();
        QuestionContentPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        radioA = new javax.swing.JRadioButton();
        radioB = new javax.swing.JRadioButton();
        radioC = new javax.swing.JRadioButton();
        radioD = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        QuestionNumberPanel = new javax.swing.JPanel();
        AlfabetLabel = new javax.swing.JLabel();
        SelesaiButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        QuestionContentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Soal");

        jLabel7.setText("*Gambar*");

        AnswerButtonGroup.add(radioA);
        radioA.setText("jRadioButton1");

        AnswerButtonGroup.add(radioB);
        radioB.setText("jRadioButton2");

        AnswerButtonGroup.add(radioC);
        radioC.setText("jRadioButton3");

        AnswerButtonGroup.add(radioD);
        radioD.setText("jRadioButton4");

        jButton6.setText("Simpan");

        javax.swing.GroupLayout QuestionContentPanelLayout = new javax.swing.GroupLayout(QuestionContentPanel);
        QuestionContentPanel.setLayout(QuestionContentPanelLayout);
        QuestionContentPanelLayout.setHorizontalGroup(
            QuestionContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuestionContentPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(110, 110, 110))
            .addGroup(QuestionContentPanelLayout.createSequentialGroup()
                .addGroup(QuestionContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuestionContentPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(QuestionContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioB)
                            .addComponent(radioA)
                            .addComponent(radioC)
                            .addComponent(radioD)))
                    .addGroup(QuestionContentPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton6))
                    .addGroup(QuestionContentPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel7)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        QuestionContentPanelLayout.setVerticalGroup(
            QuestionContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionContentPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addComponent(radioA)
                .addGap(18, 18, 18)
                .addComponent(radioB)
                .addGap(18, 18, 18)
                .addComponent(radioC)
                .addGap(18, 18, 18)
                .addComponent(radioD)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        QuestionNumberPanel.setBackground(new java.awt.Color(0, 255, 255));
        QuestionNumberPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AlfabetLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AlfabetLabel.setText("Alfabet");

        SelesaiButton.setText("Selesai");
        SelesaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelesaiButtonActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout QuestionNumberPanelLayout = new javax.swing.GroupLayout(QuestionNumberPanel);
        QuestionNumberPanel.setLayout(QuestionNumberPanelLayout);
        QuestionNumberPanelLayout.setHorizontalGroup(
            QuestionNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionNumberPanelLayout.createSequentialGroup()
                .addGroup(QuestionNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuestionNumberPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(AlfabetLabel))
                    .addGroup(QuestionNumberPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(QuestionNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SelesaiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        QuestionNumberPanelLayout.setVerticalGroup(
            QuestionNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuestionNumberPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(AlfabetLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SelesaiButton)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(QuestionNumberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuestionContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuestionContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuestionNumberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelesaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelesaiButtonActionPerformed
        StartPage startPage= new StartPage();
        startPage.setVisible(true);
        dispose(); // Close the current frame
    }//GEN-LAST:event_SelesaiButtonActionPerformed


//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(QuizAlfabet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(QuizAlfabet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(QuizAlfabet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(QuizAlfabet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QuizAlfabet().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlfabetLabel;
    private javax.swing.ButtonGroup AnswerButtonGroup;
    private javax.swing.JPanel QuestionContentPanel;
    private javax.swing.JPanel QuestionNumberPanel;
    private javax.swing.JButton SelesaiButton;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioA;
    private javax.swing.JRadioButton radioB;
    private javax.swing.JRadioButton radioC;
    private javax.swing.JRadioButton radioD;
    // End of variables declaration//GEN-END:variables
}
