/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sapasemua.view;

/**
 *
 * @author juven
 */
public class QuizAlfabet extends javax.swing.JFrame {

    /**
     * Creates new form QuizAlfabet
     */
    public QuizAlfabet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AnswerButtonGroup = new javax.swing.ButtonGroup();
        QuestionContentPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        QuestionNumberPanel = new javax.swing.JPanel();
        AlfabetLabel = new javax.swing.JLabel();
        SelesaiButton = new javax.swing.JButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        QuestionContentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Soal");

        jLabel7.setText("*Gambar*");

        AnswerButtonGroup.add(jRadioButton1);
        jRadioButton1.setText("jRadioButton1");

        AnswerButtonGroup.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton2");

        AnswerButtonGroup.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton3");

        AnswerButtonGroup.add(jRadioButton4);
        jRadioButton4.setText("jRadioButton4");

        jButton6.setText("Simpan");

        javax.swing.GroupLayout QuestionContentPanelLayout = new javax.swing.GroupLayout(QuestionContentPanel);
        QuestionContentPanel.setLayout(QuestionContentPanelLayout);
        QuestionContentPanelLayout.setHorizontalGroup(
            QuestionContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuestionContentPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(110, 110, 110))
            .addGroup(QuestionContentPanelLayout.createSequentialGroup()
                .addGroup(QuestionContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuestionContentPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(QuestionContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)))
                    .addGroup(QuestionContentPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton6))
                    .addGroup(QuestionContentPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel7)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        QuestionContentPanelLayout.setVerticalGroup(
            QuestionContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionContentPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        QuestionNumberPanel.setBackground(new java.awt.Color(0, 255, 255));
        QuestionNumberPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AlfabetLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AlfabetLabel.setText("Alfabet");

        SelesaiButton.setText("Selesai");
        SelesaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelesaiButtonActionPerformed(evt);
            }
        });

        jRadioButton5.setText("Soal 1");

        jRadioButton6.setText("Soal 2");

        jRadioButton7.setText("Soal 3");

        jRadioButton8.setText("Soal 4");

        jRadioButton9.setText("Soal 5");

        javax.swing.GroupLayout QuestionNumberPanelLayout = new javax.swing.GroupLayout(QuestionNumberPanel);
        QuestionNumberPanel.setLayout(QuestionNumberPanelLayout);
        QuestionNumberPanelLayout.setHorizontalGroup(
            QuestionNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionNumberPanelLayout.createSequentialGroup()
                .addGroup(QuestionNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuestionNumberPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(AlfabetLabel))
                    .addGroup(QuestionNumberPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(SelesaiButton))
                    .addGroup(QuestionNumberPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton5))
                    .addGroup(QuestionNumberPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton6))
                    .addGroup(QuestionNumberPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton7))
                    .addGroup(QuestionNumberPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton8))
                    .addGroup(QuestionNumberPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton9)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        QuestionNumberPanelLayout.setVerticalGroup(
            QuestionNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuestionNumberPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(AlfabetLabel)
                .addGap(33, 33, 33)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton9)
                .addGap(39, 39, 39)
                .addComponent(SelesaiButton)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(QuestionNumberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuestionContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuestionContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuestionNumberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelesaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelesaiButtonActionPerformed
        StartPage startPage= new StartPage();
        startPage.setVisible(true);
        dispose(); // Close the current frame
    }//GEN-LAST:event_SelesaiButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizAlfabet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizAlfabet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizAlfabet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizAlfabet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizAlfabet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlfabetLabel;
    private javax.swing.ButtonGroup AnswerButtonGroup;
    private javax.swing.JPanel QuestionContentPanel;
    private javax.swing.JPanel QuestionNumberPanel;
    private javax.swing.JButton SelesaiButton;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables
}
